### ISSUE TITLE
Remove hard coded Collaborator in Project View

### ISSUE THREAD

**Issue by zerefwayne** [Cynthesize/frontend#44]
### Expected Result (ER):
Collaborators are shown only when they exist. Otherwise display a text "Nothing to show." in the contributors card.

### Actual Result (AR):
A blank collaborator is being displayed.

### STR:
1. http://localhost:4200/project/8-Tweeter/view

### Screenshots:
![image](https://user-images.githubusercontent.com/28949397/51615108-0ea2bd80-1f4d-11e9-8891-d3473aab9ff8.png)

**Comment by thesmallstar** [comment]
@zerefwayne  I think we can work on 3 issues at a time now. I will do this.
