### ISSUE TITLE
Project time and creator to be displayed only if they exist.

### ISSUE THREAD

**Issue by zerefwayne** [Cynthesize/frontend#45]
### Expected Result (ER):
Project creation time and creator must be displayed only if they exist. Apply seperate conditions incase either of them is absent.

### Actual Result (AR):
`Created on by` is displayed.

### STR:
1. http://localhost:4200/project/8-Tweeter/view

### Screenshots:
![image](https://user-images.githubusercontent.com/28949397/51615394-bfa95800-1f4d-11e9-8816-43ff67e22dfb.png)

**Comment by thesmallstar** [comment]
@opencodebot claim

**Comment by zerefwayne** [comment]
You can work on this.
