### ISSUE TITLE
Write GraphQL endpoint to fetch user contributions on profile page

### ISSUE THREAD

**Issue by WickedBrat** [Cynthesize/frontend#51]
On the Profile page, there are two tabs namely `projects` and `ideas`. These tabs should display the latest 6 ideas and projects created by the user. 

Write a GraphQL query to fetch user contributions and make respective function in `profile.service.ts`

For clarifications and other help. Contact at the [Gitter Channel](https://gitter.im/Cynthesize-gitter/Lobby)

**Comment by thesmallstar** [comment]
I will try to do it :) 
I am very new to GraphQL.

**Comment by thesmallstar** [comment]
@WickedBrat  the gitter channel link seems not to be working, I am little confused on how things are working in the backend here,  and the database structure.

**Comment by WickedBrat** [comment]
@thesmallstar it's updated now

**Comment by sourabh1031** [comment]
@WickedBrat i am new to graphql and angular .  will i be able to solve this.
