### ISSUE TITLE
Add slideshow on the home page

### ISSUE THREAD

**Issue by WickedBrat** [Cynthesize/frontend#52]
Add a slideshow on the route `/home`, i.e. in the `home.component.html` which displays 3-4 images and changes after a fixed interval automatically.

**Comment by punisher1151** [comment]
can I try this ?

**Comment by WickedBrat** [comment]
Sure go ahead!

**Comment by thesmallstar** [comment]
@punisher1151  are you working on this issue?

**Comment by WickedBrat** [comment]
@thesmallstar, there hasn't been any activity on this issue since past 3 days. You may start working on it.

**Comment by thesmallstar** [comment]
Okay. :)

**Comment by thesmallstar** [comment]
@WickedBrat  Have you decided on what images do I need to add, and the width of slider for the desktop users. 
For now I have planned for - 70% of desktop width and dummy images.

**Comment by WickedBrat** [comment]
@thesmallstar the width needs to be if the full width and the dummy images work for now! :+1: The slider will be replacing the banner that is on the home page. The height also needs to be around 400px-450px (whatever value suits best)
