### ISSUE TITLE
Fix Project URL for multiple words

### ISSUE THREAD

**Issue by WickedBrat** [Cynthesize/frontend#56]
**Describe the bug**
When the project name is added with spaces, then the project URL generated contains `%20` in between the URLs. 

**To Reproduce**
1. Go to `/project/add`.
2. Type a project name like `An awesome app`
3. Submit the project.

**Expected behavior**
The project URL generated should be something like `5-An-awesome-app`, rather it gets redirected to `5-An%20awesome%20app` and the API call is done for the same.

**Comment by thesmallstar** [comment]
@WickedBrat  I have fixed this issue in my version. But when I updated my repo with the current verion, something seems to be changed and now no longer the user is redirected to the project page, but instead to home. am I missing something?
