### ISSUE TITLE
Black bottom border appears on hovering add idea/add project

### ISSUE THREAD

**Issue by WickedBrat** [Cynthesize/frontend#82]
![peek 2019-02-05 22-18](https://user-images.githubusercontent.com/45864807/52289617-66511800-2994-11e9-9224-9aa3302d8b4a.gif)

**Comment by prijeshb** [comment]
can I go for it?

**Comment by WickedBrat** [comment]
Sure!

**Comment by prijeshb** [comment]
There is problem with header class with link reference while hovering on button.
` &:hover {
      //border-bottom: 2px solid white; causes blinking of border` 
For now I have commented it!!
We can set different for both of them if required.
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/16492616/52463496-0d080500-2b9d-11e9-85fa-73c9509ac7ef.gif)

**Comment by WickedBrat** [comment]
Looks good to me. You may create a PR for this

**Comment by prijeshb** [comment]
@WickedBrat 
but this will remove hovering effect  on idea feed

**Comment by WickedBrat** [comment]
I'm moot on this one. @zerefwayne, What's your opinion?

**Comment by WickedBrat** [comment]
Also, create a PR for this, we can have the discussion there.
