### ISSUE TITLE
Trim names of projects and ideas with spaces

### ISSUE THREAD

**Issue by WickedBrat** [Cynthesize/frontend#86]
The names of any project or any idea shouldn't be of type `"   name   "` or `"    name"`. Rather it should trim all the values of the extra spaces between words. 

```javascript
Use the following script:

var string = "   An awesome    Idea   ";
string.replace(/\s+/g,' ').trim();

>>> string
    "An awesome Idea";

```

**Comment by thesmallstar** [comment]
I will do it :)
